name: apn_crashlytics
description: A new Appnormal flutter package for crash monitoring that wraps Sentry and Firebase Crashlytics.
version: 2.0.2-null-safety
homepage: https://github.com/appnormal/apn_crashlytics

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sentry: ^3.0.1
#  Using this fork for now because the original plugin is still based on the fabric sdk
  firebase_crashlytics: ^0.1.4+1
  device_info: '>=0.4.0 <2.0.0'
  package_info: '>=0.4.0 <2.0.0'
  connectivity: '>=0.4.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
